### ISSUE TITLE
Is it possible to use Polygon?

### ISSUE THREAD

**Issue by macelai** [rumblefishdev/hardhat-kms-signer#1]
Hey, thank you for creating this library, is it possible to use Polygon network with this? I tried but I got this error:

```
$ npx hardhat run scripts/deploy.ts --network mumbai
No need to generate any newer typings.
💡 Deploying
Error: Chain with ID 80001 not supported
```

**Comment by kowalski** [comment]
I'd think it should work. Can you share your hardhat.config.ts ?

**Comment by trentfoley** [comment]
I am running into this same issue.  Here is my hardhat.config.ts:
...
networks: {
    maticmumbai: {
      url: "https://polygon-mumbai.g.alchemy.com/v2/xxxxx",
      gasPrice: 50000000000, // 50 GWei
      gasMultiplier: 2,
      kmsKeyId: "xxxxx"
    }
}
...

**Comment by kowalski** [comment]
@cezary-stroczynski please close this issue when you verify it works in 1.0.0

**Comment by cezary-stroczynski** [comment]
Tested on mumbai and ropsten. Both are working now.
